global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'postgresql'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]